// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_O_vcLuiPOh0sYak-YV2Tl0_JkgElZG8',
    appId: '1:1048032281830:web:4c857301ed55f368786727',
    messagingSenderId: '1048032281830',
    projectId: 'hotel-booking-b5197',
    authDomain: 'hotel-booking-b5197.firebaseapp.com',
    storageBucket: 'hotel-booking-b5197.appspot.com',
    measurementId: 'G-X8FHKLELS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC226UJy0fuPiZC10bcPWK8vfyB2pSoccc',
    appId: '1:1048032281830:android:59bac97936fca8a7786727',
    messagingSenderId: '1048032281830',
    projectId: 'hotel-booking-b5197',
    storageBucket: 'hotel-booking-b5197.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHhBmivYabiaP_-heq3sFosPqDFozxJU',
    appId: '1:1048032281830:ios:d2135d8b87e8e29a786727',
    messagingSenderId: '1048032281830',
    projectId: 'hotel-booking-b5197',
    storageBucket: 'hotel-booking-b5197.appspot.com',
    iosBundleId: 'com.example.hotelBooking',
  );
}
