// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDe8jeOCq5OxsIenEFs-AE0zTEg5bb3A',
    appId: '1:853373948992:web:95e56f753f7d4a4b3a3ba5',
    messagingSenderId: '853373948992',
    projectId: 'hotel-bookings-968d2',
    authDomain: 'hotel-bookings-968d2.firebaseapp.com',
    storageBucket: 'hotel-bookings-968d2.appspot.com',
    measurementId: 'G-9REFL6GCJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsajbDfC9uUU4C7eXzQPeHvVjan8M3ADw',
    appId: '1:853373948992:android:5a4c06b160a0a85a3a3ba5',
    messagingSenderId: '853373948992',
    projectId: 'hotel-bookings-968d2',
    storageBucket: 'hotel-bookings-968d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonqa0LWqkkbQBOlOIrU_I5IYos0Sf4Ac',
    appId: '1:853373948992:ios:113b6beb5982a69f3a3ba5',
    messagingSenderId: '853373948992',
    projectId: 'hotel-bookings-968d2',
    storageBucket: 'hotel-bookings-968d2.appspot.com',
    iosClientId: '853373948992-24t8kis0k539126b4f04if2782u68amr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelBooking',
  );

}